version: '3'

services:
  nextjs-app:
    build: .
    expose:
      - "7777:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs-app